Fix CLI headers already sent error
This is a test patch based on PR #15742 intended to fix a problem that the CiviCRM extension has been encountering since J3.8.0 with its CLI cron script not working on PHP 7.0:
Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/html/membership/libraries/joomla/session/handler/joomla.php on line 48
Error: Failed to start application: Failed to start the session because headers have already been sent by "/var/www/html/membership/libraries/joomla/session/handler/joomla.php" at line 48.